/**
 * Holy AI Engine — adaptive LLM layer on top of the strategy stack.
 *
 * What it does:
 *   1. scoreSetup(setup, ctx)   → re-scores a triggered setup using LLM
 *                                  judgment over geometry, regime, news.
 *                                  Multiplies into the strategy's own
 *                                  confidence so weak setups never reach
 *                                  Telegram even if the strategy fired.
 *   2. commentary(setup, ctx)   → one-line natural-language read appended
 *                                  to the Telegram alert.
 *   3. marketRegime()           → cached 30-min classification of the
 *                                  current market (trend / range / chop /
 *                                  news-driven). Used by /regime command
 *                                  and (future) by strategies for adaptive
 *                                  thresholds.
 *   4. coachTrades(days)        → 1-2 sentence coaching on recent trades.
 *
 * Design rules:
 *   - NEVER throw — every public function returns a safe default if the
 *     LLM is offline, errors out, or the key is missing. Trading flow must
 *     never break because the AI layer is down.
 *   - Cache aggressively. Per-setup scores cached forever (each setupId
 *     fires once). Regime cached per 30-min bucket. Coaching cached per
 *     NY date.
 *   - Strict structured output. We parse JSON from the LLM; if parsing
 *     fails we fall back to the no-op default rather than guessing.
 *   - The engine is OPT-IN via runtime-config (aiEngine.enabled). Defaults
 *     to ON; user can toggle via /ai-engine off when they want raw
 *     strategy output without AI gating.
 */

import { oneShot, pickProvider, providerLabel } from './llm.js';
import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const CACHE_FILE = join(__dirname, '..', 'state', 'holy-ai-cache.json');

// ─── Cache ───────────────────────────────────────────────────────────────
// Persisted to disk so restarts don't re-spend the LLM budget on the same
// setupIds. Lazy-loaded on first access; flushed on every write.

let cache = null;
function loadCache() {
  if (cache) return cache;
  if (!existsSync(CACHE_FILE)) { cache = { setups: {}, regime: null, coaching: {} }; return cache; }
  try { cache = JSON.parse(readFileSync(CACHE_FILE, 'utf8')); }
  catch { cache = { setups: {}, regime: null, coaching: {} }; }
  cache.setups ||= {}; cache.coaching ||= {};
  return cache;
}
function flushCache() {
  try {
    mkdirSync(dirname(CACHE_FILE), { recursive: true });
    const tmp = CACHE_FILE + '.tmp';
    writeFileSync(tmp, JSON.stringify(cache, null, 2));
    renameSync(tmp, CACHE_FILE);
  } catch {}
}

// ─── Public defaults ─────────────────────────────────────────────────────
// Returned when LLM is offline so callers always get a usable shape.

function noopScore(originalConfidence) {
  return {
    score: 1.0,
    reasoning: '(AI offline)',
    adjusted_confidence: originalConfidence,
    aiEnabled: false,
  };
}

function noopCommentary() {
  return { text: '', aiEnabled: false };
}

function noopRegime() {
  return { regime: 'unknown', confidence: 0, summary: 'AI offline', aiEnabled: false };
}

// ─── Setup scoring ───────────────────────────────────────────────────────

/**
 * Re-score a setup using LLM judgment. Cached per setupId — same setup is
 * never re-scored even across process restarts.
 *
 * @param {object} setup    detector result (must have setupId, strategy, direction, geometry, entryPlan)
 * @param {object} ctx      optional extras: { regime, news, instrumentMeta }
 * @returns {Promise<{ score, reasoning, adjusted_confidence, aiEnabled }>}
 */
export async function scoreSetup(setup, ctx = {}) {
  const provider = pickProvider();
  if (!provider) return noopScore(setup.confidence);

  const c = loadCache();
  if (c.setups[setup.setupId]) return c.setups[setup.setupId];

  const prompt = buildScorePrompt(setup, ctx);
  let raw;
  try {
    raw = await oneShot({
      system: SCORE_SYSTEM,
      userParts: [{ kind: 'text', text: prompt }],
      maxTokens: 400,
    });
  } catch (err) {
    console.error('[holy-ai] scoreSetup LLM failed:', err.message);
    return noopScore(setup.confidence);
  }

  const parsed = parseScoreReply(raw, setup.confidence);
  c.setups[setup.setupId] = parsed;
  flushCache();
  return parsed;
}

const SCORE_SYSTEM = [
  'You are a senior prop-trading risk analyst reviewing setups generated by a quant strategy engine.',
  'Your job is to filter out low-quality setups even when the mechanical strategy fired.',
  'Use cold judgment: a clean entry in a hostile regime is worse than a messy entry in a friendly one.',
  '',
  'Respond ONLY with strict JSON (no markdown fences, no prose) matching this shape exactly:',
  '{ "score": 0.0..1.0, "reasoning": "one short sentence" }',
  '',
  'Scoring rubric:',
  '  1.0     = textbook setup, A+ context, would size up',
  '  0.7-0.9 = solid setup, standard size',
  '  0.4-0.6 = mediocre — regime is mixed, sweep weak, or news risk',
  '  0.0-0.3 = avoid — counter-trend, blown structure, or news blackout imminent',
].join('\n');

function buildScorePrompt(setup, ctx) {
  const g = setup.geometry || {};
  const ep = setup.entryPlan || {};
  const lines = [
    `Strategy: ${setup.strategy} (${setup.setupName || ''})`,
    `Instrument: ${setup.instrument || '?'} (${setup.symbol || '?'})`,
    `Direction: ${setup.direction || '?'}`,
    `Original confidence: ${(setup.confidence * 100).toFixed(0)}%`,
    `Status: ${setup.status}`,
    '',
    'Geometry:',
    g.target?.level    ? `  · liquidity target: ${g.target.name || 'pool'} @ ${g.target.level.toFixed(2)}` : '  · no clean target',
    g.sweep?.wickPrice ? `  · sweep wick @ ${g.sweep.wickPrice.toFixed(2)}` : '  · no sweep recorded',
    g.mss?.brokenPrice ? `  · MSS broken @ ${g.mss.brokenPrice.toFixed(2)}` : '  · no MSS',
    g.fvg?.top != null ? `  · FVG ${g.fvg.bottom.toFixed(2)}-${g.fvg.top.toFixed(2)}` : '  · no FVG',
  ];
  if (ep.entry != null) {
    const rr = ep.t1 && ep.stop ? Math.abs((ep.t1 - ep.entry) / (ep.entry - ep.stop)).toFixed(2) : '?';
    lines.push(
      '',
      'Entry plan:',
      `  · entry ${ep.entry.toFixed(2)} · stop ${ep.stop?.toFixed(2) || '?'} · t1 ${ep.t1?.toFixed(2) || '?'} (RR ${rr})`
    );
  }
  if (ctx.regime?.regime && ctx.regime.regime !== 'unknown') {
    lines.push('', `Current regime: ${ctx.regime.regime} (conf ${(ctx.regime.confidence * 100).toFixed(0)}%) — ${ctx.regime.summary}`);
  }
  if (ctx.news) lines.push('', `News context: ${ctx.news}`);
  if (setup.summary) lines.push('', `Strategy summary: ${setup.summary}`);
  return lines.join('\n');
}

function parseScoreReply(raw, originalConfidence) {
  // The LLM is instructed to return strict JSON. Strip stray fences just in case.
  const cleaned = String(raw || '').replace(/^```(?:json)?\s*|\s*```$/g, '').trim();
  let obj;
  try { obj = JSON.parse(cleaned); }
  catch {
    // Last-ditch: regex out the first JSON-ish blob
    const m = cleaned.match(/\{[\s\S]*\}/);
    if (m) try { obj = JSON.parse(m[0]); } catch { obj = null; }
  }
  if (!obj || typeof obj.score !== 'number') {
    console.error('[holy-ai] could not parse score reply:', cleaned.slice(0, 200));
    return noopScore(originalConfidence);
  }
  const score = Math.max(0, Math.min(1, obj.score));
  return {
    score,
    reasoning: String(obj.reasoning || '').slice(0, 200) || '(no reasoning)',
    adjusted_confidence: Math.max(0, Math.min(1, originalConfidence * score)),
    aiEnabled: true,
  };
}

// ─── Commentary ──────────────────────────────────────────────────────────
// Short trader-voice read of the setup. Goes into the Telegram alert.

/**
 * Generate a 1-line commentary for the user. Returns '' on failure.
 * Cached per setupId.
 */
export async function commentary(setup, ctx = {}) {
  const provider = pickProvider();
  if (!provider) return noopCommentary();

  const c = loadCache();
  const key = `cmt:${setup.setupId}`;
  if (c.setups[key]) return c.setups[key];

  const prompt = [
    'Setup just triggered:',
    `  strategy ${setup.strategy} · ${setup.instrument || '?'} · ${setup.direction}`,
    setup.entryPlan?.entry ? `  entry ${setup.entryPlan.entry.toFixed(2)} · stop ${setup.entryPlan.stop?.toFixed(2) || '?'} · t1 ${setup.entryPlan.t1?.toFixed(2) || '?'}` : '',
    setup.summary ? `  strategy says: ${setup.summary}` : '',
    ctx.regime?.regime ? `  regime: ${ctx.regime.regime} — ${ctx.regime.summary || ''}` : '',
    '',
    'Write ONE short sentence (≤120 chars) in a senior prop-trader voice. No emoji, no preamble.',
    'Reference what to watch, what could invalidate, or the regime fit. No advice to the user — they already know to take or skip.',
  ].filter(Boolean).join('\n');

  let raw;
  try {
    raw = await oneShot({
      system: 'You are a terse senior prop trader. One sentence only. No emoji.',
      userParts: [{ kind: 'text', text: prompt }],
      maxTokens: 100,
    });
  } catch (err) {
    console.error('[holy-ai] commentary LLM failed:', err.message);
    return noopCommentary();
  }
  const text = String(raw || '').replace(/^["']|["']$/g, '').replace(/\s+/g, ' ').trim().slice(0, 180);
  const out = { text, aiEnabled: true };
  c.setups[key] = out;
  flushCache();
  return out;
}

// ─── Market regime ───────────────────────────────────────────────────────
// Cached for 30 minutes. Reads quote_snapshot from cloud_data_supplement so
// we never hit the LLM more than ~48 times a day per provider.

const REGIME_TTL_MS = 30 * 60 * 1000;

/**
 * Classify the current market into a regime. Cached 30min.
 * @returns {Promise<{ regime, confidence, summary, aiEnabled }>}
 */
export async function marketRegime() {
  const provider = pickProvider();
  if (!provider) return noopRegime();

  const c = loadCache();
  if (c.regime && (Date.now() - c.regime.at) < REGIME_TTL_MS) {
    return c.regime.value;
  }

  // Build a minimal snapshot the LLM can reason about.
  let snapshot;
  try {
    snapshot = await buildRegimeSnapshot();
  } catch (err) {
    console.error('[holy-ai] regime snapshot failed:', err.message);
    return noopRegime();
  }
  if (!snapshot) return noopRegime();

  const prompt = [
    'Snapshot of current market conditions across the three primary instruments.',
    '',
    snapshot,
    '',
    'Classify the current regime. Respond ONLY with strict JSON:',
    '{ "regime": "trend" | "range" | "chop" | "news-driven" | "reversal", "confidence": 0..1, "summary": "<=120 char summary" }',
  ].join('\n');

  let raw;
  try {
    raw = await oneShot({
      system: 'You are a quant macro analyst. Strict JSON only. No prose, no fences.',
      userParts: [{ kind: 'text', text: prompt }],
      maxTokens: 200,
    });
  } catch (err) {
    console.error('[holy-ai] regime LLM failed:', err.message);
    return noopRegime();
  }

  const value = parseRegimeReply(raw);
  c.regime = { at: Date.now(), value };
  flushCache();
  return value;
}

async function buildRegimeSnapshot() {
  // Pull what we already cache locally — no extra network beyond what
  // cloud_data_supplement already does.
  try {
    const cd = await import('./cloud_data_supplement.js');
    const panes = await cd.fetchAllPanes();
    const lines = [];
    for (const inst of ['gold', 'nasdaq', 'sp']) {
      const p60 = panes.get(`${inst}|60`);
      const p15 = panes.get(`${inst}|15`);
      const bars = p15?.bars || p60?.bars || [];
      if (bars.length < 20) continue;
      const last = bars[bars.length - 1];
      const first = bars[Math.max(0, bars.length - 20)];
      const change = ((last.close - first.close) / first.close) * 100;
      const hi = Math.max(...bars.slice(-20).map((b) => b.high));
      const lo = Math.min(...bars.slice(-20).map((b) => b.low));
      const range = ((hi - lo) / first.close) * 100;
      lines.push(`  · ${inst}: last ${last.close.toFixed(2)} · 20-bar Δ ${change.toFixed(2)}% · range ${range.toFixed(2)}%`);
    }
    if (lines.length === 0) return null;

    // News blackout context
    let news = '';
    try {
      const { checkBlackout, nextEvent } = await import('./news.js');
      const bo = checkBlackout(Date.now() / 1000, 30);
      if (bo.blocked && bo.event) news = `news blackout ACTIVE: ${bo.event.title || 'event'} (${bo.minutesAway}m)`;
      else {
        const nxt = nextEvent(Date.now() / 1000);
        if (nxt) news = `next high-impact event: ${nxt.title || '?'} in ${nxt.minutesAway}m`;
      }
    } catch {}

    return [
      'Instrument snapshot (last 20 bars on 15m or 60m):',
      ...lines,
      news ? '' : null,
      news || null,
    ].filter((l) => l !== null).join('\n');
  } catch {
    return null;
  }
}

function parseRegimeReply(raw) {
  const cleaned = String(raw || '').replace(/^```(?:json)?\s*|\s*```$/g, '').trim();
  let obj;
  try { obj = JSON.parse(cleaned); }
  catch {
    const m = cleaned.match(/\{[\s\S]*\}/);
    if (m) try { obj = JSON.parse(m[0]); } catch { obj = null; }
  }
  if (!obj) return noopRegime();
  return {
    regime: String(obj.regime || 'unknown'),
    confidence: Math.max(0, Math.min(1, Number(obj.confidence) || 0)),
    summary: String(obj.summary || '').slice(0, 200) || '(no summary)',
    aiEnabled: true,
  };
}

// ─── Trade coaching ──────────────────────────────────────────────────────

/**
 * Generate 1-2 sentence coaching based on recent trades. Cached per NY date
 * so /coach can be called many times without spamming the LLM.
 */
export async function coachTrades(days = 7) {
  const provider = pickProvider();
  if (!provider) return { text: 'AI offline — no coaching available.', aiEnabled: false };

  const c = loadCache();
  const todayKey = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/New_York', year: 'numeric', month: '2-digit', day: '2-digit',
  }).format(new Date()).replace(/\D/g, '');
  const cacheKey = `${todayKey}:${days}`;
  if (c.coaching[cacheKey]) return c.coaching[cacheKey];

  // Pull recent closed trades
  let trades = [];
  try {
    const journal = await import('./trade_journal.js');
    const all = journal.recentTrades(100);
    const sinceMs = Date.now() - days * 86_400_000;
    trades = all.filter((t) => {
      const ts = Date.parse(t.openedAt || t.ts || '') || 0;
      return ts >= sinceMs;
    });
  } catch {}
  if (trades.length === 0) {
    const out = { text: 'No trades in the last ' + days + ' days to coach on.', aiEnabled: true };
    c.coaching[cacheKey] = out; flushCache();
    return out;
  }

  // Compact summary for the LLM
  const summary = trades.slice(0, 40).map((t) => {
    const exit = t.exitReason ? `${t.exitReason.toUpperCase()}@${t.exitPrice}` : 'open';
    return `${t.setupId} · ${t.strategy || '?'} · ${t.direction || '?'} · entry ${t.entryPrice} → ${exit}`;
  }).join('\n');

  let raw;
  try {
    raw = await oneShot({
      system: 'You are a trading coach. Read the trade log. Return 1-2 short, specific, actionable sentences. No emoji, no preamble. Reference a concrete pattern you see.',
      userParts: [{ kind: 'text', text: `Last ${trades.length} trades (newest first):\n\n${summary}` }],
      maxTokens: 200,
    });
  } catch (err) {
    console.error('[holy-ai] coach LLM failed:', err.message);
    return { text: `Coaching unavailable: ${err.message}`, aiEnabled: false };
  }

  const text = String(raw || '').replace(/^["']|["']$/g, '').trim().slice(0, 400);
  const out = { text: text || 'No patterns surfaced in this window.', aiEnabled: true };
  c.coaching[cacheKey] = out; flushCache();
  return out;
}

// ─── Configuration helpers ───────────────────────────────────────────────

const RUNTIME_CONFIG_FILE = join(__dirname, '..', 'state', 'runtime-config.json');

/**
 * Resolve whether the engine is enabled. Reads runtime-config; defaults true.
 * Also returns the gate threshold (default 0.55 of adjusted confidence).
 *
 * Sync function — reads the config file directly so the trading loop can
 * call it on every tick without an `await`.
 */
export function getEngineConfig() {
  let cfg = {};
  try { if (existsSync(RUNTIME_CONFIG_FILE)) cfg = JSON.parse(readFileSync(RUNTIME_CONFIG_FILE, 'utf8')); } catch {}
  return {
    enabled: cfg.aiEngine?.enabled !== false,           // default true
    threshold: Number(cfg.aiEngine?.threshold) || 0.55,
    provider: providerLabel(),
  };
}

/** Manually clear all caches. Useful from /clearchat or admin commands. */
export function clearCache() {
  cache = { setups: {}, regime: null, coaching: {} };
  flushCache();
}
